importers:
- name: "orc"
  mode: "api"
  includeInSchedule: true
- name: "ams"
  mode: "api"
  includeInSchedule: true
- name: "bwps"
  mode: "api"
  includeInSchedule: true
- name: "sailsys-boats"
  mode: "directory"
  includeInSchedule: true
- name: "sailsys-boats"
  mode: "api"
  includeInSchedule: true
- name: "sailsys-races"
  mode: "directory"
  includeInSchedule: true
- name: "sailsys-races"
  mode: "api"
  includeInSchedule: true
- name: "topyacht"
  mode: "api"
  includeInSchedule: true
- name: "analysis"
  mode: "run"
  includeInSchedule: true
- name: "reference-factors"
  mode: "run"
  includeInSchedule: true
schedule:
  days:
  - "WEDNESDAY"
  time: "09:56:00"
lastSailSysIds:
  sailsys-races-api: 40809
  sailsys-boats-api: 14937
targetIrcYear: 2025
outlierSigma: null
mergeCandidateThreshold: 0.5
fuzzyMatchThreshold: 0.9
